NAME	= libtf.a
CC		= cc
CFLAGS	= -Wall -Wextra -Werror
SRCDIR	= srcs
INCDIR	= includes
SRCS	= $(SRCDIR)/ft_putchar.c \
		$(SRCDIR)/ft_putstr.c \
		$(SRCDIR)/ft_strcmp.c \
		$(SRCDIR)/ft_strlen.c \
		$(SRCDIR)/ft_swap.c \
OBJS	=$(SRCS:.c=.0)
all:	$(NAME)
